/*
 * This file is generated by jOOQ.
 */
package com.broughty.ttlptwit.database.jooq.data.tables;


import com.broughty.ttlptwit.database.jooq.data.DefaultSchema;
import com.broughty.ttlptwit.database.jooq.data.Keys;
import com.broughty.ttlptwit.database.jooq.data.tables.records.MissingUserRecord;
import java.time.LocalDateTime;
import java.util.function.Function;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MissingUser extends TableImpl<MissingUserRecord> {

    /**
     * The reference instance of <code>MISSING_USER</code>
     */
    public static final  MissingUser                                  MISSING_USER     = new MissingUser();
    private static final long                                         serialVersionUID = 1L;
    /**
     * The column <code>MISSING_USER.ID</code>.
     */
    public final         TableField<MissingUserRecord, Long>
                                                                      ID               =
        createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");
    /**
     * The column <code>MISSING_USER.USER_ID</code>.
     */
    public final         TableField<MissingUserRecord, String>
                                                                      USER_ID          =
        createField(DSL.name("USER_ID"), SQLDataType.VARCHAR(64).nullable(false), this, "");
    /**
     * The column <code>MISSING_USER.UPDATED_AT</code>.
     */
    public final         TableField<MissingUserRecord, LocalDateTime>
                                                                      UPDATED_AT       =
        createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");
    /**
     * The column <code>MISSING_USER.ACTIVE</code>.
     */
    public final         TableField<MissingUserRecord, Boolean>
                                                                      ACTIVE           =
        createField(DSL.name("ACTIVE"), SQLDataType.BOOLEAN.defaultValue(DSL.field("TRUE", SQLDataType.BOOLEAN)), this, "");
    /**
     * The column <code>MISSING_USER.CREATED_DATE</code>.
     */
    public final         TableField<MissingUserRecord, LocalDateTime>
                                                                      CREATED_DATE     =
        createField(DSL.name("CREATED_DATE"), SQLDataType.LOCALDATETIME(6), this, "");

    private MissingUser(Name alias, Table<MissingUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private MissingUser(Name alias, Table<MissingUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>MISSING_USER</code> table reference
     */
    public MissingUser(String alias) {
        this(DSL.name(alias), MISSING_USER);
    }

    /**
     * Create an aliased <code>MISSING_USER</code> table reference
     */
    public MissingUser(Name alias) {
        this(alias, MISSING_USER);
    }

    /**
     * Create a <code>MISSING_USER</code> table reference
     */
    public MissingUser() {
        this(DSL.name("MISSING_USER"), null);
    }

    public <O extends Record> MissingUser(Table<O> child, ForeignKey<O, MissingUserRecord> key) {
        super(child, key, MISSING_USER);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MissingUserRecord> getRecordType() {
        return MissingUserRecord.class;
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<MissingUserRecord, Long> getIdentity() {
        return (Identity<MissingUserRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<MissingUserRecord> getPrimaryKey() {
        return Keys.PK_MISSING_USER;
    }

    @Override
    public MissingUser as(String alias) {
        return new MissingUser(DSL.name(alias), this);
    }

    @Override
    public MissingUser as(Name alias) {
        return new MissingUser(alias, this);
    }

    @Override
    public MissingUser as(Table<?> alias) {
        return new MissingUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MissingUser rename(String name) {
        return new MissingUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MissingUser rename(Name name) {
        return new MissingUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MissingUser rename(Table<?> name) {
        return new MissingUser(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, LocalDateTime, Boolean, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super String, ? super LocalDateTime, ? super Boolean, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class, Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType,
                                      Function5<? super Long, ? super String, ? super LocalDateTime, ? super Boolean, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
