/*
 * This file is generated by jOOQ.
 */
package com.broughty.ttlptwit.database.jooq.data.tables.records;


import com.broughty.ttlptwit.database.jooq.data.tables.ListeningPartyTweet;
import java.time.LocalDateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ListeningPartyTweetRecord extends UpdatableRecordImpl<ListeningPartyTweetRecord> implements
    Record15<Long, String, Integer, String, String, String, LocalDateTime, Integer, Integer, Integer, Integer, String, String, Boolean, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.TWEET_ID</code>.
     */
    public void setTweetId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.TWEET_ID</code>.
     */
    public String getTweetId() {
        return (String) get(1);
    }

    /**
     * Create a detached, initialised ListeningPartyTweetRecord
     */
    public ListeningPartyTweetRecord(Long id,
                                     String tweetId,
                                     Integer ttlpNo,
                                     String text,
                                     String author,
                                     String inReplyToUserid,
                                     LocalDateTime createdAt,
                                     Integer likes,
                                     Integer quote,
                                     Integer reply,
                                     Integer retweet,
                                     String geo,
                                     String attachments,
                                     Boolean active,
                                     LocalDateTime createdDate) {
        super(ListeningPartyTweet.LISTENING_PARTY_TWEET);

        setId(id);
        setTweetId(tweetId);
        setTtlpNo(ttlpNo);
        setText(text);
        setAuthor(author);
        setInReplyToUserid(inReplyToUserid);
        setCreatedAt(createdAt);
        setLikes(likes);
        setQuote(quote);
        setReply(reply);
        setRetweet(retweet);
        setGeo(geo);
        setAttachments(attachments);
        setActive(active);
        setCreatedDate(createdDate);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.TTLP_NO</code>.
     */
    public Integer getTtlpNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.TEXT</code>.
     */
    public void setText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.TEXT</code>.
     */
    public String getText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.AUTHOR</code>.
     */
    public void setAuthor(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.AUTHOR</code>.
     */
    public String getAuthor() {
        return (String) get(4);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.IN_REPLY_TO_USERID</code>.
     */
    public void setInReplyToUserid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.IN_REPLY_TO_USERID</code>.
     */
    public String getInReplyToUserid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.LIKES</code>.
     */
    public void setLikes(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.LIKES</code>.
     */
    public Integer getLikes() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.QUOTE</code>.
     */
    public void setQuote(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.QUOTE</code>.
     */
    public Integer getQuote() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.REPLY</code>.
     */
    public void setReply(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.REPLY</code>.
     */
    public Integer getReply() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.RETWEET</code>.
     */
    public void setRetweet(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.RETWEET</code>.
     */
    public Integer getRetweet() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.GEO</code>.
     */
    public void setGeo(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.GEO</code>.
     */
    public String getGeo() {
        return (String) get(11);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.ATTACHMENTS</code>.
     */
    public void setAttachments(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.ATTACHMENTS</code>.
     */
    public String getAttachments() {
        return (String) get(12);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.TTLP_NO</code>.
     */
    public void setTtlpNo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.ACTIVE</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.ACTIVE</code>.
     */
    public void setActive(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>LISTENING_PARTY_TWEET.CREATED_DATE</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>LISTENING_PARTY_TWEET.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(14, value);
    }

    @Override
    public Row15<Long, String, Integer, String, String, String, LocalDateTime, Integer, Integer, Integer, Integer, String, String, Boolean, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Field<Long> field1() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.ID;
    }

    @Override
    public Field<String> field2() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.TWEET_ID;
    }

    @Override
    public Row15<Long, String, Integer, String, String, String, LocalDateTime, Integer, Integer, Integer, Integer, String, String, Boolean, LocalDateTime> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<String> field4() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.TEXT;
    }

    @Override
    public Field<String> field5() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.AUTHOR;
    }

    @Override
    public Field<String> field6() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.IN_REPLY_TO_USERID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.CREATED_AT;
    }

    @Override
    public Field<Integer> field8() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.LIKES;
    }

    @Override
    public Field<Integer> field9() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.QUOTE;
    }

    @Override
    public Field<Integer> field10() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.REPLY;
    }

    @Override
    public Field<Integer> field11() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.RETWEET;
    }

    @Override
    public Field<String> field12() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.GEO;
    }

    @Override
    public Field<String> field13() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.ATTACHMENTS;
    }

    @Override
    public Field<Integer> field3() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.TTLP_NO;
    }

    @Override
    public Field<Boolean> field14() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.ACTIVE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTweetId();
    }

    @Override
    public Field<LocalDateTime> field15() {
        return ListeningPartyTweet.LISTENING_PARTY_TWEET.CREATED_DATE;
    }

    @Override
    public String component4() {
        return getText();
    }

    @Override
    public String component5() {
        return getAuthor();
    }

    @Override
    public String component6() {
        return getInReplyToUserid();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public Integer component8() {
        return getLikes();
    }

    @Override
    public Integer component9() {
        return getQuote();
    }

    @Override
    public Integer component10() {
        return getReply();
    }

    @Override
    public Integer component11() {
        return getRetweet();
    }

    @Override
    public String component12() {
        return getGeo();
    }

    @Override
    public String component13() {
        return getAttachments();
    }

    @Override
    public Integer component3() {
        return getTtlpNo();
    }

    @Override
    public Boolean component14() {
        return getActive();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTweetId();
    }

    @Override
    public LocalDateTime component15() {
        return getCreatedDate();
    }

    @Override
    public String value4() {
        return getText();
    }

    @Override
    public String value5() {
        return getAuthor();
    }

    @Override
    public String value6() {
        return getInReplyToUserid();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public Integer value8() {
        return getLikes();
    }

    @Override
    public Integer value9() {
        return getQuote();
    }

    @Override
    public Integer value10() {
        return getReply();
    }

    @Override
    public Integer value11() {
        return getRetweet();
    }

    @Override
    public String value12() {
        return getGeo();
    }

    @Override
    public String value13() {
        return getAttachments();
    }

    @Override
    public Integer value3() {
        return getTtlpNo();
    }

    @Override
    public Boolean value14() {
        return getActive();
    }

    @Override
    public ListeningPartyTweetRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value2(String value) {
        setTweetId(value);
        return this;
    }

    @Override
    public LocalDateTime value15() {
        return getCreatedDate();
    }

    @Override
    public ListeningPartyTweetRecord value4(String value) {
        setText(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value5(String value) {
        setAuthor(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value6(String value) {
        setInReplyToUserid(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value8(Integer value) {
        setLikes(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value9(Integer value) {
        setQuote(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value10(Integer value) {
        setReply(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value11(Integer value) {
        setRetweet(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value12(String value) {
        setGeo(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value13(String value) {
        setAttachments(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value3(Integer value) {
        setTtlpNo(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value14(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public ListeningPartyTweetRecord value15(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListeningPartyTweetRecord
     */
    public ListeningPartyTweetRecord() {
        super(ListeningPartyTweet.LISTENING_PARTY_TWEET);
    }

    @Override
    public ListeningPartyTweetRecord values(Long value1,
                                            String value2,
                                            Integer value3,
                                            String value4,
                                            String value5,
                                            String value6,
                                            LocalDateTime value7,
                                            Integer value8,
                                            Integer value9,
                                            Integer value10,
                                            Integer value11,
                                            String value12,
                                            String value13,
                                            Boolean value14,
                                            LocalDateTime value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }
}
