/*
 * This file is generated by jOOQ.
 */
package com.broughty.ttlptwit.database.jooq.data.tables.records;


import com.broughty.ttlptwit.database.jooq.data.tables.MissingUser;
import java.time.LocalDateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MissingUserRecord extends UpdatableRecordImpl<MissingUserRecord>
    implements Record5<Long, String, LocalDateTime, Boolean, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached MissingUserRecord
     */
    public MissingUserRecord() {
        super(MissingUser.MISSING_USER);
    }

    /**
     * Create a detached, initialised MissingUserRecord
     */
    public MissingUserRecord(Long id, String userId, LocalDateTime updatedAt, Boolean active, LocalDateTime createdDate) {
        super(MissingUser.MISSING_USER);

        setId(id);
        setUserId(userId);
        setUpdatedAt(updatedAt);
        setActive(active);
        setCreatedDate(createdDate);
    }

    /**
     * Getter for <code>MISSING_USER.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>MISSING_USER.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>MISSING_USER.USER_ID</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MISSING_USER.USER_ID</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MISSING_USER.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>MISSING_USER.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>MISSING_USER.ACTIVE</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>MISSING_USER.ACTIVE</code>.
     */
    public void setActive(Boolean value) {
        set(3, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>MISSING_USER.CREATED_DATE</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>MISSING_USER.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    @Override
    public Row5<Long, String, LocalDateTime, Boolean, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, LocalDateTime, Boolean, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MissingUser.MISSING_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return MissingUser.MISSING_USER.USER_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return MissingUser.MISSING_USER.UPDATED_AT;
    }

    @Override
    public Field<Boolean> field4() {
        return MissingUser.MISSING_USER.ACTIVE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return MissingUser.MISSING_USER.CREATED_DATE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserId();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public Boolean component4() {
        return getActive();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserId();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public Boolean value4() {
        return getActive();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public MissingUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MissingUserRecord value2(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public MissingUserRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public MissingUserRecord value4(Boolean value) {
        setActive(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public MissingUserRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public MissingUserRecord values(Long value1, String value2, LocalDateTime value3, Boolean value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
