/*
 * This file is generated by jOOQ.
 */
package com.broughty.ttlptwit.database.jooq.data;


import com.broughty.ttlptwit.database.jooq.data.tables.ListeningParty;
import com.broughty.ttlptwit.database.jooq.data.tables.ListeningPartyTweet;
import com.broughty.ttlptwit.database.jooq.data.tables.ListeningPartyUser;
import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>LISTENING_PARTY</code>.
     */
    public final ListeningParty LISTENING_PARTY = ListeningParty.LISTENING_PARTY;

    /**
     * The table <code>LISTENING_PARTY_TWEET</code>.
     */
    public final ListeningPartyTweet LISTENING_PARTY_TWEET = ListeningPartyTweet.LISTENING_PARTY_TWEET;

    /**
     * The table <code>LISTENING_PARTY_USER</code>.
     */
    public final ListeningPartyUser LISTENING_PARTY_USER = ListeningPartyUser.LISTENING_PARTY_USER;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ListeningParty.LISTENING_PARTY,
            ListeningPartyTweet.LISTENING_PARTY_TWEET,
            ListeningPartyUser.LISTENING_PARTY_USER
        );
    }
}
