/*
 * This file is generated by jOOQ.
 */
package com.broughty.ttlptwit.database.jooq.data;


import com.broughty.ttlptwit.database.jooq.data.tables.ListeningParty;
import com.broughty.ttlptwit.database.jooq.data.tables.ListeningPartyTweet;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>LISTENING_PARTY</code>.
     */
    public static final ListeningParty LISTENING_PARTY = ListeningParty.LISTENING_PARTY;

    /**
     * The table <code>LISTENING_PARTY_TWEET</code>.
     */
    public static final ListeningPartyTweet LISTENING_PARTY_TWEET = ListeningPartyTweet.LISTENING_PARTY_TWEET;
}
